# Generated by Django 2.0.5 on 2018-11-17 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_user_phoneno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=None, to='doctor.Doctor'),
        ),
        migrations.AlterField(
            model_name='user',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=None, to='patient.Patient'),
        ),
    ]
