# Generated by Django 2.0.5 on 2018-11-17 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_auto_20181117_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='cvv',
            field=models.FloatField(),
        ),
    ]
