# Generated by Django 2.0.5 on 2018-11-17 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0008_auto_20181117_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='zip5',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
