# Generated by Django 2.0.5 on 2018-11-17 15:34

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0009_auto_20181117_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('doctor', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=25), size=None)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=None, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
