# Generated by Django 2.0.5 on 2018-11-17 18:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0010_visit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('participants', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=25), size=None)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='messagerecipient',
            name='message',
        ),
        migrations.RemoveField(
            model_name='messagerecipient',
            name='messageUserGroup',
        ),
        migrations.RemoveField(
            model_name='messagerecipient',
            name='recipient',
        ),
        migrations.AlterUniqueTogether(
            name='messageusergroup',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='messageusergroup',
            name='group',
        ),
        migrations.RemoveField(
            model_name='messageusergroup',
            name='user',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='attachmentName',
            new_name='localName',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='thumbnailURL',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='message',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='message',
            name='mimeType',
        ),
        migrations.RemoveField(
            model_name='message',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='message',
            name='size',
        ),
        migrations.AlterField(
            model_name='message',
            name='messageType',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='MessageGroup',
        ),
        migrations.DeleteModel(
            name='MessageRecipient',
        ),
        migrations.DeleteModel(
            name='MessageUserGroup',
        ),
        migrations.AddField(
            model_name='message',
            name='room',
            field=models.ForeignKey(default=None, on_delete=None, to='patient.Room'),
            preserve_default=False,
        ),
    ]
