# Generated by Django 2.0.5 on 2018-11-17 20:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0012_auto_20181117_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='visit',
            field=models.ForeignKey(default=1, on_delete=None, to='patient.Visit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visit',
            name='endAt',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 17, 20, 10, 42, 591956, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
