# Generated by Django 2.0.5 on 2018-11-17 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0012_auto_20181117_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='localName',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
