# Generated by Django 2.0.5 on 2018-11-17 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0013_auto_20181117_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='endAt',
            field=models.DateTimeField(null=True),
        ),
    ]
