# Generated by Django 2.0.5 on 2018-11-17 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0013_auto_20181117_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='attachmentDisplayName',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='messages',
            name='messageType',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
