# Generated by Django 2.0.5 on 2018-11-17 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0014_auto_20181117_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='visit',
            field=models.ForeignKey(default=1, on_delete=None, to='patient.Visit'),
            preserve_default=False,
        ),
    ]
