# Generated by Django 2.0.5 on 2018-11-17 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssn', models.CharField(max_length=10, null=True)),
                ('pcpId', models.CharField(max_length=10, null=True)),
                ('insuranceNo', models.CharField(max_length=10, null=True)),
                ('creditcardNo', models.CharField(max_length=16, null=True)),
            ],
        ),
    ]
