# Generated by Django 2.0.5 on 2018-11-17 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='creditcardNo',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='insuranceNo',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='ssn',
        ),
        migrations.AddField(
            model_name='doctor',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='speciality',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='pcpId',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
