# Generated by Django 2.0.5 on 2018-11-17 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_auto_20181117_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='lastseen',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
